name: E2E

on:
  workflow_run:
    workflows: ["Go Unit Test"]
    types: [completed]
    
jobs:

  E2E:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: E2E
      run: docker-compose up --build --abort-on-container-exit
      working-directory: e2e
      env:
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"


